image:
  repository: 700800570325.dkr.ecr.ap-south-1.amazonaws.com/dev-gitops-app
  tag: 73b575122cf1ef4821c8081fb2780e6248aa454d
  pullPolicy: Always
replicaCount: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 80
