image:
  repository: 700800570325.dkr.ecr.ap-south-1.amazonaws.com/dev-gitops-app
  tag: 9c93544200bb164fe2eccf9d665575ca7b1af7a0
  pullPolicy: Always
replicaCount: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 80
