image:
  repository: 700800570325.dkr.ecr.ap-south-1.amazonaws.com/dev-gitops-app
  tag: c870a884e03ab1220d9234a5b9c2b5ce24aea240
  pullPolicy: Always
replicaCount: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 80
